Added HEalth Tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,13 +9,13 @@ jobs:
     docker:
         runs-on: ubuntu-latest
         env:
+            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
             DATABASE_URL: ${{ secrets.DATABASE_URL }}
             JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
             GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
             CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
             CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
             CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
-            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         steps:
             - name: Cloning Repository
               uses: actions/checkout@v4
@@ -26,13 +26,26 @@ jobs:
             - name: Container Status
               run: docker ps
 
-            - name: Pushing to DockerHub
+            - name: Checking Backend
+              run: |
+                for i in $(seq 1 15); do
+                  if curl -fs http://localhost:8000/health >/dev/null; then
+                    echo "Backend Working"; exit 0
+                  fi
+                  echo "waiting for backend... ($i)"; sleep 2
+                done
+                echo "Backend Failed"; docker compose logs backend; exit 1
+
+            - name: Login to DockerHub
               uses: docker/login-action@v3
               with:
                 username: ${{ secrets.DOCKER_USERNAME }}
-                password: ${{ secrets.DOCKER_TOKEN }}
+                password: ${{ secrets.DOCKER_PASSWORD }}
 
-            - run: docker push "$DOC"
+            - name: Push images
+              run: |
+                docker push "${{ secrets.DOCKER_USERNAME }}/blogsphere-frontend:latest"
+                docker push "${{ secrets.DOCKER_USERNAME }}/blogsphere-backend:latest"
 
             - name: Closing Containers
               run: docker compose down
